<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PetLar.Application\PetLar.Application.csproj" />
    <ProjectReference Include="..\PetLar.Infrastructure\PetLar.Infrastructure.csproj" />
  </ItemGroup>

</Project>
